version: '3'

services:
  # Consul Cluster #
  consul1:
    image: consul:latest
    hostname: consul1
    command: consul agent -server -client=0.0.0.0 -ui -bootstrap -log-level warn -data-dir=/tmp/consuldata
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    expose:
      - "8300"
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"

  # Api Gateway and Load Balancer #
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --consulcatalog.endpoint=consul1:8500
    ports:
      - "81:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Infrastructure/ApiGateway/traefik.toml:/etc/traefik/traefik.toml
      - ./Infrastructure/Security/:/etc/traefik/ssl/
    depends_on:
      - "consul1"
    links:
      - "consul1"

  # Application Services #
  microservices-auth:
    image: microservices-auth
    build:
      context: ./Microservices.Auth
      dockerfile: Dockerfile.prod
    environment:
      - "SERVICE_TAGS=traefik.enable=true,traefik.frontend.rule=Host:accounts.microservices.com"

  # Docker Registrator #
  registrator:
    depends_on:
      - consul1
    image: gliderlabs/registrator:master
    command: -internal consul://consul1:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul1